---- QUERY 1 ----
-- Add data into the `account table`
INSERT INTO public.account (account_firstname,
        account_lastname,
		account_email,
		account_password)
VALUES ('Tony', 'Stark', 'tony@starkent.com', 'Iam1ronM@n');

---- QUERY 2 ----
-- Update account_id=1 in the `account table`
UPDATE public.account
SET account_type = 'Admin'
WHERE account_id = 1;

---- QUERY 3 ----
-- Delete data from the `account table`
DELETE FROM public.account
WHERE account_id=1;

---- Query 4 ----
-- Update GM Hummer data from the `inventory table`
UPDATE public.inventory
SET inv_description = REPLACE(inv_description, 'small interiors', 'a huge interior')
WHERE inv_make = 'GM'AND inv_model = 'Hummer' AND classification_id = 4;

---- Query 5 ----
-- Using Select & Inner join statment  table`
SELECT inv_make, inv_model, classification_name 
FROM public.inventory
JOIN public.classification
USING(classification_id)
WHERE classification_name = 'Sport';

-- Query 6
-- Updating inv_image & inv_thumbnail in the `inventory table`
UPDATE public.inventory
SET inv_image = REPLACE(inv_image, '/images/', 'images/'),
    inv_thumbnail = REPLACE(inv_thumbnail, '/images/', 'images/');

-- Add likes_count column to the `inventory table`
ALTER TABLE public.inventory
ADD likes_count INT NOT NULL DEFAULT 0;

--Create favorite table Query
CREATE TABLE IF NOT EXISTS public.favorites(
    fav_id INT GENERATED BY DEFAULT AS IDENTITY,
    account_id INT NOT NULL,
    inv_id INT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT favorite_pkey PRIMARY KEY (fav_id),
    CONSTRAINT unique_favorite UNIQUE(account_id, inv_id),
    CONSTRAINT favorites_account_fk FOREIGN KEY (account_id) REFERENCES public.account (account_id) MATCH SIMPLE ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT favorites_inventory_fk FOREIGN KEY (inv_id) REFERENCES public.inventory (inv_id) MATCH SIMPLE ON UPDATE CASCADE ON DELETE CASCADE
);

--- Create ENUM(TYPE) for order status
CREATE TYPE public.status_type AS ENUM ('successful','pending','failed');

--- Create orders table
CREATE TABLE IF NOT EXISTS public.orders(
    order_id INT GENERATED BY DEFAULT AS IDENTITY,
    account_id INT NOT NULL,
    total_price NUMERIC(9, 2) NOT NULL,
    status status_type NOT NULL DEFAULT 'pending'::status_type,
    order_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT orders_pkey PRIMARY KEY (order_id),
    CONSTRAINT fk_account FOREIGN KEY (account_id) REFERENCES public.account (account_id) MATCH SIMPLE ON UPDATE CASCADE ON DELETE NO ACTION
);

--- Create orderItems table
CREATE TABLE IF NOT EXISTS public.order_items(
    order_item_id INT GENERATED BY DEFAULT AS IDENTITY,
    order_id INT NOT NULL,
    inv_id INT NOT NULL,
    quantity INT NOT NULL,
    price NUMERIC(9, 2) NOT NULL,
    CONSTRAINT order_items_pkey PRIMARY KEY (order_item_id),
    CONSTRAINT fk_orders FOREIGN KEY (order_id) REFERENCES public.orders (order_id) MATCH SIMPLE ON UPDATE CASCADE ON DELETE NO ACTION,
    CONSTRAINT fk_inventory FOREIGN KEY (inv_id) REFERENCES public.inventory (inv_id) MATCH SIMPLE ON UPDATE CASCADE ON DELETE NO ACTION
);

---Add Icon field to the classification table
--AlTER TABLE public.classification
--ADD icon_class VARCHAR(100);

---- updating a mistaken image name in the `inventory table`
--UPDATE public.inventory
--SET inv_image = REPLACE(inv_image, 'vcamaro.jpg', 'camaro.jpg')
--WHERE inv_model = 'Camaro';