-- 1. Create custom ENUM types
CREATE TYPE public.account_type AS ENUM ('Client', 'Employee', 'Admin');
ALTER TYPE public.account_type OWNER TO cse340motordb_xhs3_user;

CREATE TYPE public.status_type AS ENUM ('successful', 'pending', 'failed');

-- 2. Create Classification Table
CREATE TABLE IF NOT EXISTS public.classification(
    classification_id INT GENERATED BY DEFAULT AS IDENTITY,
    classification_name CHARACTER VARYING NOT NULL,
    icon_class VARCHAR(100) NOT NULL,
    CONSTRAINT classification_pk PRIMARY KEY (classification_id)
);

-- 3. Create Account Table
CREATE TABLE IF NOT EXISTS public.account (
    account_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    account_firstname character varying NOT NULL,
    account_lastname character varying NOT NULL,
    account_email character varying NOT NULL,
    account_password character varying NOT NULL,
    account_type account_type NOT NULL DEFAULT 'Client'::account_type,
    CONSTRAINT account_pkey PRIMARY KEY (account_id)
);

-- 4. Create Inventory Table (Updated with User ID Relationship)
CREATE TABLE IF NOT EXISTS public.inventory(
    inv_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    inv_make character varying NOT NULL,
    inv_model character varying NOT NULL,
    inv_year character(4) NOT NULL,
    inv_description text NOT NULL,
    inv_image character varying NOT NULL,
    inv_thumbnail character varying NOT NULL,
    inv_price numeric(9, 0) NOT NULL,
    inv_miles integer NOT NULL,
    inv_color character varying NOT NULL,
    classification_id integer NOT NULL,
    likes_count INT NOT NULL DEFAULT 0,
    account_id integer NULL, -- Identifies who is selling the car (NULL means corporate stock)
    inv_approved BOOLEAN NOT NULL DEFAULT FALSE, -- Requires review before going live
    CONSTRAINT inventory_pkey PRIMARY KEY(inv_id),
    CONSTRAINT fk_classification FOREIGN KEY (classification_id) REFERENCES public.classification (classification_id) MATCH SIMPLE ON UPDATE CASCADE ON DELETE NO ACTION,
    CONSTRAINT fk_account_owner FOREIGN KEY (account_id) REFERENCES public.account (account_id) MATCH SIMPLE ON UPDATE CASCADE ON DELETE SET NULL
);

-- 5. Create Favorites Table
CREATE TABLE IF NOT EXISTS public.favorites(
    fav_id INT GENERATED BY DEFAULT AS IDENTITY,
    account_id INT NOT NULL,
    inv_id INT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT favorite_pkey PRIMARY KEY (fav_id),
    CONSTRAINT unique_favorite UNIQUE(account_id, inv_id),
    CONSTRAINT favorites_account_fk FOREIGN KEY (account_id) REFERENCES public.account (account_id) MATCH SIMPLE ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT favorites_inventory_fk FOREIGN KEY (inv_id) REFERENCES public.inventory (inv_id) MATCH SIMPLE ON UPDATE CASCADE ON DELETE CASCADE
);

-- 6. Create Orders Table
CREATE TABLE IF NOT EXISTS public.orders(
    order_id INT GENERATED BY DEFAULT AS IDENTITY,
    account_id INT NOT NULL,
    total_price NUMERIC(9, 2) NOT NULL,
    status status_type NOT NULL DEFAULT 'pending'::status_type,
    order_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT orders_pkey PRIMARY KEY (order_id),
    CONSTRAINT fk_account FOREIGN KEY (account_id) REFERENCES public.account (account_id) MATCH SIMPLE ON UPDATE CASCADE ON DELETE NO ACTION
);

-- 7. Create Order Items Table
CREATE TABLE IF NOT EXISTS public.order_items(
    order_item_id INT GENERATED BY DEFAULT AS IDENTITY,
    order_id INT NOT NULL,
    inv_id INT NOT NULL,
    quantity INT NOT NULL,
    price NUMERIC(9, 2) NOT NULL,
    CONSTRAINT order_items_pkey PRIMARY KEY (order_item_id),
    CONSTRAINT fk_orders FOREIGN KEY (order_id) REFERENCES public.orders (order_id) MATCH SIMPLE ON UPDATE CASCADE ON DELETE NO ACTION,
    CONSTRAINT fk_inventory FOREIGN KEY (inv_id) REFERENCES public.inventory (inv_id) MATCH SIMPLE ON UPDATE CASCADE ON DELETE NO ACTION
);