-- 1. Create custom ENUM types
CREATE TYPE public.account_type AS ENUM ('Client', 'Employee', 'Admin');
ALTER TYPE public.account_type OWNER TO cse340motordb_xhs3_user;

CREATE TYPE public.status_type AS ENUM ('successful', 'pending', 'failed');

-- ====================================================================
-- CREATE CORE BUSINESS WORKFLOW ENUMS (Locked System Logic)
-- ====================================================================
CREATE TYPE public.application_status_enum AS ENUM (
    'PENDING_REVIEW', 
    'UNDERWRITING', 
    'APPROVED', 
    'DENIED'
);

CREATE TYPE public.contract_status_enum AS ENUM (
    'ACTIVE', 
    'OVERDUE',
    'DEFAULTED', 
    'SETTLED'
);

CREATE TYPE public.payment_status_enum AS ENUM (
    'COMPLETED', 
    'FAILED', 
    'REFUNDED'
);

-- 2. Create Classification Table
CREATE TABLE IF NOT EXISTS public.classification(
    classification_id INT GENERATED BY DEFAULT AS IDENTITY,
    classification_name CHARACTER VARYING NOT NULL,
    icon_class VARCHAR(100) NOT NULL,
    CONSTRAINT classification_pk PRIMARY KEY (classification_id)
);

-- 3. Create Account Table
CREATE TABLE IF NOT EXISTS public.account (
    account_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    account_firstname character varying NOT NULL,
    account_lastname character varying NOT NULL,
    account_email character varying NOT NULL,
    account_password character varying NOT NULL,
    account_type account_type NOT NULL DEFAULT 'Client'::account_type,
    CONSTRAINT account_pkey PRIMARY KEY (account_id)
);

-- 4. Create Inventory Table (Updated with User ID Relationship)
CREATE TABLE IF NOT EXISTS public.inventory(
    inv_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    inv_make character varying NOT NULL,
    inv_model character varying NOT NULL,
    inv_year character(4) NOT NULL,
    inv_description text NOT NULL,
    inv_image character varying NOT NULL,
    inv_thumbnail character varying NOT NULL,
    inv_price numeric(9, 0) NOT NULL,
    inv_miles integer NOT NULL,
    inv_color character varying NOT NULL,
    classification_id integer NOT NULL,
    likes_count INT NOT NULL DEFAULT 0,
    account_id integer NULL, -- Identifies who is selling the car (NULL means corporate stock)
    inv_approved BOOLEAN NOT NULL DEFAULT FALSE, -- Requires review before going live
    CONSTRAINT inventory_pkey PRIMARY KEY(inv_id),
    CONSTRAINT fk_classification FOREIGN KEY (classification_id) REFERENCES public.classification (classification_id) MATCH SIMPLE ON UPDATE CASCADE ON DELETE NO ACTION,
    CONSTRAINT fk_account_owner FOREIGN KEY (account_id) REFERENCES public.account (account_id) MATCH SIMPLE ON UPDATE CASCADE ON DELETE SET NULL
);

-- 5. Create Favorites Table
CREATE TABLE IF NOT EXISTS public.favorites(
    fav_id INT GENERATED BY DEFAULT AS IDENTITY,
    account_id INT NOT NULL,
    inv_id INT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT favorite_pkey PRIMARY KEY (fav_id),
    CONSTRAINT unique_favorite UNIQUE(account_id, inv_id),
    CONSTRAINT favorites_account_fk FOREIGN KEY (account_id) REFERENCES public.account (account_id) MATCH SIMPLE ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT favorites_inventory_fk FOREIGN KEY (inv_id) REFERENCES public.inventory (inv_id) MATCH SIMPLE ON UPDATE CASCADE ON DELETE CASCADE
);

-- 6. Create Orders Table
CREATE TABLE IF NOT EXISTS public.orders(
    order_id INT GENERATED BY DEFAULT AS IDENTITY,
    account_id INT NOT NULL,
    total_price NUMERIC(9, 2) NOT NULL,
    status status_type NOT NULL DEFAULT 'pending'::status_type,
    order_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT orders_pkey PRIMARY KEY (order_id),
    CONSTRAINT fk_account FOREIGN KEY (account_id) REFERENCES public.account (account_id) MATCH SIMPLE ON UPDATE CASCADE ON DELETE NO ACTION
);

-- 7. Create Order Items Table
CREATE TABLE IF NOT EXISTS public.order_items(
    order_item_id INT GENERATED BY DEFAULT AS IDENTITY,
    order_id INT NOT NULL,
    inv_id INT NOT NULL,
    quantity INT NOT NULL,
    price NUMERIC(9, 2) NOT NULL,
    CONSTRAINT order_items_pkey PRIMARY KEY (order_item_id),
    CONSTRAINT fk_orders FOREIGN KEY (order_id) REFERENCES public.orders (order_id) MATCH SIMPLE ON UPDATE CASCADE ON DELETE NO ACTION,
    CONSTRAINT fk_inventory FOREIGN KEY (inv_id) REFERENCES public.inventory (inv_id) MATCH SIMPLE ON UPDATE CASCADE ON DELETE NO ACTION
);

-- Dynamic bucket for classifications (e.g., 'LEASE', 'FINANCE', 'EQUITY_LINE')
CREATE TABLE IF NOT EXISTS public.tier_classifications_catalog (
    classification_id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    classification_name VARCHAR(50) NOT NULL UNIQUE
);

-- Dynamic bucket for display names (e.g., 'Bespoke Asset Leasing', 'Direct Capital Acquisition')
CREATE TABLE IF NOT EXISTS public.tier_names_catalog (
    name_id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    display_name VARCHAR(100) NOT NULL UNIQUE
);

-- The unified tier pricing configuration table
CREATE TABLE IF NOT EXISTS public.finance_tiers (
    tier_id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name_id INT NOT NULL, 
    classification_id INT NOT NULL, 
    base_apr NUMERIC(4, 2) NOT NULL, 
    min_term_months INT NOT NULL DEFAULT 24,
    max_term_months INT NOT NULL DEFAULT 72,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    
    CONSTRAINT fk_tier_name FOREIGN KEY (name_id) REFERENCES public.tier_names_catalog(name_id) ON DELETE RESTRICT,
    CONSTRAINT fk_tier_classification FOREIGN KEY (classification_id) REFERENCES public.tier_classifications_catalog(classification_id) ON DELETE RESTRICT
);

-- User Submission Ledger (Points to our new dynamic tiers)
CREATE TABLE IF NOT EXISTS public.finance_applications (
    application_id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    account_id INT NOT NULL, 
    inv_id INT NULL, 
    tier_id INT NOT NULL, 
    
    desired_capital_amount NUMERIC(12, 2) NOT NULL, 
    preferred_term_months INT NOT NULL, 
    application_purpose VARCHAR(50) NOT NULL, 
    estimated_annual_income NUMERIC(12, 2) NOT NULL,
    
    -- Handled securely via the pipeline ENUM
    application_status public.application_status_enum NOT NULL DEFAULT 'PENDING_REVIEW', 
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    
    CONSTRAINT fk_application_account FOREIGN KEY (account_id) REFERENCES public.account (account_id) ON DELETE CASCADE,
    CONSTRAINT fk_application_inventory FOREIGN KEY (inv_id) REFERENCES public.inventory (inv_id) ON DELETE SET NULL,
    CONSTRAINT fk_application_tier FOREIGN KEY (tier_id) REFERENCES public.finance_tiers (tier_id)
);

-- The Legal Agreement Table (Final terms locked down here)
CREATE TABLE IF NOT EXISTS public.underwriting_contracts (
    contract_id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    application_id INT NOT NULL UNIQUE, 
    contract_reference_number VARCHAR(60) NOT NULL UNIQUE, 
    
    final_capital_funded NUMERIC(12, 2) NOT NULL,
    final_apr NUMERIC(4, 2) NOT NULL, 
    contract_term_months INT NOT NULL,
    down_payment_received NUMERIC(12, 2) NOT NULL DEFAULT 0.00,
    exact_monthly_payment NUMERIC(12, 2) NOT NULL, 
    maturity_date DATE NOT NULL,
    
    -- Handled securely via the contract lifecycle ENUM
    contract_status public.contract_status_enum NOT NULL DEFAULT 'ACTIVE', 
    notes TEXT NULL, 
    activated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    
    CONSTRAINT fk_contract_application FOREIGN KEY (application_id) REFERENCES public.finance_applications (application_id) ON DELETE RESTRICT
);

-- CSE34 Motors Monthly Payment Tracking Ledger
CREATE TABLE IF NOT EXISTS public.finance_payments (
    payment_id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    contract_id INT NOT NULL, 
    amount_paid NUMERIC(12, 2) NOT NULL, 
    payment_date TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    payment_status public.payment_status_enum NOT NULL DEFAULT 'COMPLETED', 
    payment_method VARCHAR(30) NOT NULL, 
    
    CONSTRAINT fk_payment_contract FOREIGN KEY (contract_id) REFERENCES public.underwriting_contracts(contract_id) ON DELETE RESTRICT
);
