CREATE TYPE public.account_type AS ENUM ('Client', 'Employee', 'Admin');
ALTER TYPE public.account_type OWNER TO cse340motordb_user;
Create Table public.classification(
    classification_id INT GENERATED BY DEFAULT AS IDENTITY,
    classification_name CHARACTER VARYING NOT NULL,
    CONSTRAINT classification_pk PRIMARY KEY (classification_id)
);
-- Table structure for table `inventory`
CREATE TABLE IF NOT EXISTS public.inventory(
    inv_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    inv_make character varying NOT NULL,
    inv_model character varying NOT NULL,
    inv_year character(4) NOT NULL,
    inv_description text NOT NULL,
    inv_image character varying NOT NULL,
    inv_thumbnail character varying NOT NULL,
    inv_price numeric(9, 0) NOT NULL,
    inv_miles integer NOT NULL,
    inv_color character varying NOT NULL,
    classification_id integer NOT NULL,
    CONSTRAINT inventiry_pkey PRIMARY KEY(inv_id)
);
-- Create relationship between `classification` and `inventory` tables
ALTER TABLE IF EXISTS public.inventory
ADD CONSTRAINT fk_classification FOREIGN KEY (classification_id) REFERENCES public.classification (classification_id) MATCH SIMPLE ON UPDATE CASCADE ON DELETE NO ACTION;
-- Table structure for table `account`
CREATE TABLE IF NOT EXISTS public.account (
    account_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    account_firstname character varying NOT NULL,
    account_lastname character varying NOT NULL,
    account_email character varying NOT NULL,
    account_password character varying NOT NULL,
    account_type account_type NOT NULL DEFAULT 'Client'::account_type,
    CONSTRAINT account_pkey PRIMARY KEY (account_id)
);

-- Data for the classification table.
INSERT INTO public.classification (classification_name, icon_class)
VALUES ('Custom','fa-crown'),
    ('Sport','fa-gauge-high'),
    ('SUV', 'fa-truck-monster'),
    ('Truck' 'fa-truck'),
    ('Sedan', 'fa-car-side'),
    ('Van', 'fa-shuttle-van'),
    ('Coupe', 'fa-car'),
    ('Hybrid','fa-leaf'),
    ('Electric','fa-bolt'),
    ('Luxury','fa-gem'),
    ('Motorcycle','fa-motorcycle'),
    ('Classic','fa-clock-rotate-left');
    
-- Data for table `inventory`
INSERT INTO public.inventory (
        inv_make,
        inv_model,
        inv_year,
        inv_description,
        inv_image,
        inv_thumbnail,
        inv_price,
        inv_miles,
        inv_color,
        classification_id
    )
VALUES (
        'Chevy',
        'Camaro',
        '2018',
        'If you want to look cool this is the ar you need! This car has great performance at an affordable price. Own it today!',
        '/images/camaro.jpg',
        '/images/camaro-tn.jpg',
        25000,
        101222,
        'Silver',
        2,
        32
    ),
    (
        'Batmobile',
        'Custom',
        '1966',
        'Iconic television vehicle custom-built by George Barris from a 1955 Lincoln Futura concept car body shell.',
        '/images/batmobile.jpg',
        '/images/batmobile-tn.jpg',
        4600000,
        29887,
        'Black',
        1,
        31
    ),
    (
        'Toyota',
        'Hilux BEV Concept',
        '2024',
        'Fully electric single-cab mid-size pickup truck prototype designed for commercial fleet use.',
        '/images/toyota_hilux_bev_2026.webp',
        '/images/toyota_hilux_bev_2026-tn.webp',
        55000,
        0,
        'white',
        1,
        21
    ),
    (
        'Toyota',
        'Hilux GR Sport II',
        '2024',
        'Performance-oriented mid-size dual-cab pickup truck featuring Gazoo Racing off-road suspension and wide-track styling.',
        '/images/toyota_hilux_gr_sportII_2024.webp',
        '/images/toyota_hilux_gr_sportII_2024-tn.webp',
        65000,
        0,
        'Red',
        4,
        44
    ),
    (
        'Toyota',
        'Hilux Double Cab 48V',
        '2024',
        'Mid-size dual-cab pickup utility vehicle equipped with a 48V mild-hybrid diesel powertrain for improved efficiency.',
        '/images/toyota_hilux Hybrid_48v_2025.webp',
        '/images/toyota_hilux Hybrid_48v_2025-tn-.webp',
        50000,
        41205,
        'Bronze',
        8,
        38
    ),
    (
        'Lamborghini',
        'Adventador',
        '2018',
        'This V-12 engine packs a punch in this sporty car. Make sure you wear your seatbelt and obey all traffic laws. ',
        '/images/adventador.jpg',
        '/images/adventador-tn.jpg',
        417000,
        71003,
        'White',
        2,
        22
    ),
    (
        'Toyota',
        '4Runner Limited',
        '2025',
        'Sixth-generation rugged mid-size SUV built on a durable body-on-frame platform.',
        '/images/Toyota_4runner_2025.webp',
        '/images/Toyota_4runner_2025-tn.webp',
        52000,
        18956,
        'Heritage Blue',
        3,
        33
    ),
    (
        'Toyota',
        'RAV4 Prime XSE',
        '2021',
        'High-performance plug-in hybrid compact crossover SUV with dual-tone styling.',
        '/images/toyota_rav4_hybrid_2024.webp',
        '/images/toyota_rav4_hybrid_2024-tn.webp',
        43000,
        3998,
        'Red',
        8,
        28
    ),
    (
        'Cadillac',
        'Escalade',
        '2019',
        'This stylin car is great for any occasion from going to the beach to meeting the president. The luxurious inside makes this car a home away from home.',
        '/images/escalade.jpg',
        '/images/escalade-tn.jpg',
        75195,
        41958,
        'Black',
        4,
        18
    ),
    (
        'GM',
        'Hummer',
        '2016',
        'Do you have 6 kids and like to go offroading? The Hummer gives you the small interiors with an engine to get you out of any muddy or rocky situation.',
        '/images/hummer.jpg',
        '/images/hummer-tn.jpg',
        58800,
        56564,
        'Yellow',
        4,
        12
    ),
    (
        'Toyota',
        'bZ4X',
        '2023',
        'All-electric compact crossover utility vehicle built on a dedicated EV platform.',
        '/images/toyota_bz4x_2025.webp',
        '/images/toyota_bz4x_2025-tn.webp',
        44000,
        200125,
        'Silver',
        9,
        39
    ),
    (
        'Toyota',
        'Hilux Invincible',
        '2021',
        'Mid-size double-cab diesel pickup truck featuring premium comfort trims and robust payload capacity.',
        '/images/truck.webp',
        '/images/truck-tn.webp',
        48000,
        26357,
        'Dark Gray',
        4,
        55
    ),
    (
        'Tesla',
        'Model 3',
        '2024',
        'All-electric compact luxury sedan featuring the refined "Highland" aerodynamic facelift.',
        '/images/tesla_model_3_2025.webp',
        '/images/tesla_model_3_2025-tn.webp',
        39000,
        128564,
        'Stealth Gray',
        9,
        23
    ),
    (
        'Tesla',
        'Model S',
        '2012',
        'Premium all-electric full-size luxury liftback sedan showcasing the original pre-facelift nosecone design.',
        '/images/tesla_model_s_2016.webp',
        '/images/tesla_model_s_2016-tn.webp',
        75000,
        38522,
        'Metallic Charcoal',
        10,
        24
    ),
    (
        'Audi',
        'R8 Coupe',
        '2014',
        'First-generation mid-engine luxury sports car featuring signature LED DRL headlights and sideblades.',
        '/images/black-audi.webp',
        '/images/black-audi-tn.webp',
        115000,
        108247,
        'Matte Black',
        2,
        34
    ),
    (
        'Ford',
        'Mustang GT Custom',
        '2013',
        'Heavily customized performance muscle coupe featuring an aftermarket body kit, slammed suspension, and deep-dish wheels.',
        '/images/black-coupe.webp',
        '/images/black-coupe-tn.webp',
        35000,
        0,
        'Black',
        1,
        20
    ),
    (
        'BMW',
        '4 Series Coupe (F32)',
        '2015',
        'Sleek luxury compact executive sports coupe featuring an M-Sport aerodynamic package.',
        '/images/bmw.webp',
        '/images/bmw-tn.webp',
        42000
        23000,
        'Black',
        7,
        45
    ),
    (
        'BMW',
        '3 Series Sedan (F30)',
        '2013',
        'Compact executive four-door luxury sports sedan styled with a blacked-out kidney grille treatment.',
        '/images/bmw-sedan.webp',
        '/images/bmw-sedan-tn.webp',
        33000,
        45000,
        'Black',
        5,
        35
    ),
    (
        'Hyundai',
        'Grandeur'
        '2023',
        'Seventh-generation full-size flagship luxury sedan featuring futuristic seamless horizon LED light bars.',
        '/images/hyundai-grandeur.webp',
        '/images/hyundai-grandeur-tn.webp',
        45000,
        15000,
        'Silver',
        10,
        23
    ),(
        'Mercedes-Benz',
        'GLS 63 AMG Custom (Larte Design)',
        '2017',
        'Luxury full-size high-performance SUV upgraded with an aggressive widebody carbon fiber aero kit by Larte Design.',
        '/images/firstslidemercedes.webp',
        '/images/firstslidemercedes-tn.webp',
        140000,
        5000,
        'Black',
        1,
        25
    ),
    (
        'Mercedes-Benz',
    )
    ;

---- Query 4 ----
-- Update GM Hummer data from the `inventory table`
UPDATE public.inventory
SET inv_description = REPLACE(inv_description, 'small interiors', 'a huge interior')
WHERE inv_make = 'GM'AND inv_model = 'Hummer' AND classification_id = 4;

-- Query 6
-- Updating inv_image & inv_thumbnail in the `inventory table`
UPDATE public.inventory
SET inv_image = REPLACE(inv_image, '/images/', 'images/vehicles/'),
    inv_thumbnail = REPLACE(inv_thumbnail, '/images/', 'images/vehicles/');