CREATE TYPE public.account_type AS ENUM ('Client', 'Employee', 'Admin');
ALTER TYPE public.account_type OWNER TO cse340motordb_xhs3_user;
Create Table public.classification(
    classification_id INT GENERATED BY DEFAULT AS IDENTITY,
    classification_name CHARACTER VARYING NOT NULL,
    icon_class VARCHAR(100) NOT NULL,
    CONSTRAINT classification_pk PRIMARY KEY (classification_id)
);
-- Table structure for table `inventory`
CREATE TABLE IF NOT EXISTS public.inventory(
    inv_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    inv_make character varying NOT NULL,
    inv_model character varying NOT NULL,
    inv_year character(4) NOT NULL,
    inv_description text NOT NULL,
    inv_image character varying NOT NULL,
    inv_thumbnail character varying NOT NULL,
    inv_price numeric(9, 0) NOT NULL,
    inv_miles integer NOT NULL,
    inv_color character varying NOT NULL,
    classification_id integer NOT NULL,
    likes_count INT NOT NULL DEFAULT 0,
    CONSTRAINT inventory_pkey PRIMARY KEY(inv_id)
);
-- Create relationship between `classification` and `inventory` tables
ALTER TABLE IF EXISTS public.inventory
ADD CONSTRAINT fk_classification FOREIGN KEY (classification_id) REFERENCES public.classification (classification_id) MATCH SIMPLE ON UPDATE CASCADE ON DELETE NO ACTION;
-- Table structure for table `account`
CREATE TABLE IF NOT EXISTS public.account (
    account_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    account_firstname character varying NOT NULL,
    account_lastname character varying NOT NULL,
    account_email character varying NOT NULL,
    account_password character varying NOT NULL,
    account_type account_type NOT NULL DEFAULT 'Client'::account_type,
    CONSTRAINT account_pkey PRIMARY KEY (account_id)
);

-- Data for the classification table.
INSERT INTO public.classification (classification_name, icon_class)
VALUES ('Custom','fa-crown'),
    ('Sport','fa-gauge-high'),
    ('SUV', 'fa-truck-monster'),
    ('Truck', 'fa-truck'),
    ('Sedan', 'fa-car-side'),
    ('Van', 'fa-shuttle-van'),
    ('Coupe', 'fa-car'),
    ('Hybrid','fa-leaf'),
    ('Electric','fa-bolt'),
    ('Luxury','fa-gem'),
    ('Motorcycle','fa-motorcycle'),
    ('Classic','fa-clock-rotate-left');
    
-- Data for table `inventory`
INSERT INTO public.inventory (
        inv_make,
        inv_model,
        inv_year,
        inv_description,
        inv_image,
        inv_thumbnail,
        inv_price,
        inv_miles,
        inv_color,
        classification_id,
        likes_count
    )
VALUES (
        'Chevy',
        'Camaro',
        '2018',
        'If you want to look cool this is the ar you need! This car has great performance at an affordable price. Own it today!',
        '/images/vehicles/camaro.jpg',
        '/images/vehicles/camaro-tn.jpg',
        25000,
        101222,
        'Silver',
        2,
        32
    ),
    (
        'Batmobile',
        'Custom',
        '1966',
        'Iconic television vehicle custom-built by George Barris from a 1955 Lincoln Futura concept car body shell.',
        '/images/vehicles/batmobile.jpg',
        '/images/vehicles/batmobile-tn.jpg',
        4600000,
        29887,
        'Black',
        1,
        31
    ),
    (
        'Toyota',
        'Hilux BEV Concept',
        '2024',
        'Fully electric single-cab mid-size pickup truck prototype designed for commercial fleet use.',
        '/images/vehicles/toyota_hilux_bev_2026.webp',
        '/images/vehicles/toyota_hilux_bev_2026-tn.webp',
        55000,
        0,
        'white',
        1,
        21
    ),
    (
        'Toyota',
        'Hilux GR Sport II',
        '2024',
        'Performance-oriented mid-size dual-cab pickup truck featuring Gazoo Racing off-road suspension and wide-track styling.',
        '/images/vehicles/toyota_hilux_gr_sportII_2024.webp',
        '/images/vehicles/toyota_hilux_gr_sportII_2024-tn.webp',
        65000,
        0,
        'Red',
        4,
        44
    ),
    (
        'Toyota',
        'Hilux Double Cab 48V',
        '2024',
        'Mid-size dual-cab pickup utility vehicle equipped with a 48V mild-hybrid diesel powertrain for improved efficiency.',
        '/images/vehicles/toyota_hilux Hybrid_48v_2025.webp',
        '/images/vehicles/toyota_hilux Hybrid_48v_2025-tn-.webp',
        50000,
        41205,
        'Bronze',
        8,
        38
    ),
    (
        'Lamborghini',
        'Adventador',
        '2018',
        'This V-12 engine packs a punch in this sporty car. Make sure you wear your seatbelt and obey all traffic laws. ',
        '/images/vehicles/adventador.jpg',
        '/images/vehicles/adventador-tn.jpg',
        417000,
        71003,
        'White',
        2,
        22
    ),
    (
        'Toyota',
        '4Runner Limited',
        '2025',
        'Sixth-generation rugged mid-size SUV built on a durable body-on-frame platform.',
        '/images/vehicles/Toyota_4runner_2025.webp',
        '/images/vehicles/Toyota_4runner_2025-tn.webp',
        52000,
        18956,
        'Heritage Blue',
        3,
        33
    ),
    (
        'Toyota',
        'RAV4 Prime XSE',
        '2021',
        'High-performance plug-in hybrid compact crossover SUV with dual-tone styling.',
        '/images/vehicles/toyota_rav4_hybrid_2024.webp',
        '/images/vehicles/toyota_rav4_hybrid_2024-tn.webp',
        43000,
        3998,
        'Red',
        8,
        28
    ),
    (
        'Cadillac',
        'Escalade',
        '2019',
        'This stylin car is great for any occasion from going to the beach to meeting the president. The luxurious inside makes this car a home away from home.',
        '/images/vehicles/escalade.jpg',
        '/images/vehicles/escalade-tn.jpg',
        75195,
        41958,
        'Black',
        4,
        18
    ),
    (
        'HUMMER',
        'H3',
        '2008',
        'Do you have 6 kids and like to go offroading? The Hummer gives you the small interiors with an engine to get you out of any muddy or rocky situation.',
        '/images/vehicles/hummer.jpg',
        '/images/vehicles/hummer-tn.jpg',
        58800,
        56564,
        'Yellow',
        4,
        12
    ),
    (
        'Toyota',
        'bZ4X',
        '2023',
        'All-electric compact crossover utility vehicle built on a dedicated EV platform.',
        '/images/vehicles/toyota_bz4x_2025.webp',
        '/images/vehicles/toyota_bz4x_2025-tn.webp',
        44000,
        200125,
        'Silver',
        9,
        39
    ),
    (
        'Toyota',
        'Hilux Invincible',
        '2021',
        'Mid-size double-cab diesel pickup truck featuring premium comfort trims and robust payload capacity.',
        '/images/vehicles/truck.webp',
        '/images/vehicles/truck-tn.webp',
        48000,
        26357,
        'Dark Gray',
        4,
        55
    ),
    (
        'Tesla',
        'Model 3',
        '2024',
        'All-electric compact luxury sedan featuring the refined "Highland" aerodynamic facelift.',
        '/images/vehicles/tesla_model_3_2025.webp',
        '/images/vehicles/tesla_model_3_2025-tn.webp',
        39000,
        128564,
        'Stealth Gray',
        9,
        23
    ),
    (
        'Tesla',
        'Model S',
        '2012',
        'Premium all-electric full-size luxury liftback sedan showcasing the original pre-facelift nosecone design.',
        '/images/vehicles/tesla_model_s_2016.webp',
        '/images/vehicles/tesla_model_s_2016-tn.webp',
        75000,
        38522,
        'Metallic Charcoal',
        10,
        24
    ),
    (
        'Audi',
        'R8 Coupe',
        '2014',
        'First-generation mid-engine luxury sports car featuring signature LED DRL headlights and sideblades.',
        '/images/vehicles/black-audi.webp',
        '/images/vehicles/black-audi-tn.webp',
        115000,
        108247,
        'Matte Black',
        2,
        34
    ),
    (
        'Ford',
        'Mustang GT Custom',
        '2013',
        'Heavily customized performance muscle coupe featuring an aftermarket body kit, slammed suspension, and deep-dish wheels.',
        '/images/vehicles/black-coupe.webp',
        '/images/vehicles/black-coupe-tn.webp',
        35000,
        0,
        'Black',
        1,
        20
    ),
    (
        'BMW',
        '4 Series Coupe (F32)',
        '2015',
        'Sleek luxury compact executive sports coupe featuring an M-Sport aerodynamic package.',
        '/images/vehicles/bmw.webp',
        '/images/vehicles/bmw-tn.webp',
        42000,
        23000,
        'Black',
        7,
        45
    ),
    (
        'BMW',
        '3 Series Sedan (F30)',
        '2013',
        'Compact executive four-door luxury sports sedan styled with a blacked-out kidney grille treatment.',
        '/images/vehicles/bmw-sedan.webp',
        '/images/vehicles/bmw-sedan-tn.webp',
        33000,
        45000,
        'Black',
        5,
        35
    ),
    (
        'Hyundai',
        'Grandeur',
        '2023',
        'Seventh-generation full-size flagship luxury sedan featuring futuristic seamless horizon LED light bars.',
        '/images/vehicles/hyundai-grandeur.webp',
        '/images/vehicles/hyundai-grandeur-tn.webp',
        45000,
        15000,
        'Silver',
        10,
        23
    ),(
        'Mercedes-Benz',
        'GLS 63 AMG Custom (Larte Design)',
        '2017',
        'Luxury full-size high-performance SUV upgraded with an aggressive widebody carbon fiber aero kit by Larte Design.',
        '/images/vehicles/firstslidemercedes.webp',
        '/images/vehicles/firstslidemercedes-tn.webp',
        140000,
        5000,
        'Black',
        1,
        25
    ),
    (
        'Mercedes-Benz',
        'G 63 AMG',
        '2016',
        'Iconic twin-turbo V8 high-performance luxury off-road vehicle with boxy military heritage styling.',
        '/images/vehicles/g-wagon.webp',
        '/images/vehicles/g-wagon-tn.webp',
        139000,
        13000,
        'Matte Black',
        3,
        30
    ),
    (
        'Hyundai',
        'Ioniq 5 N',
        '2024',
        'High-performance, all-electric crossover featuring track-optimized dual motors, aggressive aero elements, and simulated paddle shifts.',
        '/images/vehicles/Hyundai-IONIQ-5N.webp',
        '/images/vehicles/Hyundai-IONIQ-5N-tn.webp',
        66000,
        0,
        'Performance Blue',
        9,
        40
    ),
    (
        'Hyundai',
        'Elantra N',
        '2024',
        'Track-ready high-performance compact sport sedan equipped with a turbocharged engine and signature red exterior trim accents.',
        '/images/vehicles/hyundai-motors-1.webp',
        '/images/vehicles/hyundai-motors-1-tn.webp',
        33000,
        0,
        'Blue',
        2,
        20
    ),
    (
        'Hyundai',
        'Santa Fe Calligraphy',
        '2024',
        'adically redesigned mid-size family SUV showcasing a boxy, futuristic aesthetic and premium interior amenities.',
        '/images/vehicles/hyundai-suv.webp',
        '/images/vehicles/hyundai-suv-tn.webp',
        47000,
        23399,
        'Terracotta Orange',
        8,
        25
    ),
    (
        'Kia',
        'F-150 Lightning',
        '2022',
        'Full-size three-row all-electric flagship SUV featuring a striking geometric design and advanced highway driving pilot features.',
        '/images/vehicles/kia-black-car.webp',
        '/images/vehicles/kia-black-car-tn.webp',
        74000,
        0,
        'Aurora Black Pearl',
        9,
        30
    ),
    (
        'Lamborghini',
        'Aventador LP700-4',
        '2012',
        'Exotic Italian supercar powered by a roaring mid-engine V12 with an angular design inspired by stealth fighter jets.',
        '/images/vehicles/orange-lambo-adventador.webp',
        '/images/vehicles/orange-lambo-adventador-tn.webp',
        393000,
        15000,
        'Arancio Argos Orange',
        2,
        20

    ),
    (
        'Mercedes-Benz',
        'A-Class Hatchback (W177)',
        '2019',
        'Premium compact luxury hatchback displaying the modern AMG-line exterior package styling cues.',
        '/images/vehicles/red-small-benz.webp',
        '/images/vehicles/red-small-benz-tn.webp',
        35000,
        20000,
        'Red',
        10, 
        30
    ),
    (
        'Genesis',
        'G80',
        '2021',
        'Elegant mid-size luxury executive sedan featuring the brand iconic crest grille and twin-line LED headlights.',
        '/images/vehicles/sedan.webp',
        '/images/vehicles/sedan-tn.webp',
        48000,
        15000,
        'Savile Silver',
        5,
        25
    ),
    (
        'Tesla',
        'Semi',
        '2023',
        'Class 8 all-electric commercial tri-motor tractor designed for heavy-duty, long-haul freight transportation.',
        '/images/vehicles/semi-truck.webp',
        '/images/vehicles/semi-truck-tn.webp',
        180000,
        0,
        'Alpine White',
        9, 
        40
    ),
    (
        'Mercedes-Benz',
        'CLA Coupe',
        '2020',
        'Sleek, subcompact luxury four-door coupe showcasing a sloping panoramic roofline and frameless doors.',
        '/images/vehicles/small-benz.webp',
        '/images/vehicles/small-benz-tn.webp',
        37000,
        12000,
        'Polar White',
        7,
        22
    ),
    (
        'Ford',
        'F-150 Lightning',
        '2022',
        'All-electric full-size pickup truck offering traditional truck capability combined with an advanced signature front LED lightbar.',
        '/images/vehicles/truck.webp',
        '/images/vehicles/truck-tn.webp',
        55000,
        0,
        'Antimatter Blue',
        9, 
        30
    )
;

---- Query 4 ----
-- Update GM Hummer data from the `inventory table`
--UPDATE public.inventory
--SET inv_description = REPLACE(inv_description, 'small interiors', 'a huge interior')
--WHERE inv_make = 'GM'AND inv_model = 'Hummer' AND classification_id = 4;

-- Query 6
-- Updating inv_image & inv_thumbnail in the `inventory table`
UPDATE public.inventory
SET inv_image = REPLACE(inv_image, '/images/', 'images/vehicles/'),
    inv_thumbnail = REPLACE(inv_thumbnail, '/images/', 'images/vehicles/');


SELECT * FROM account;

DELETE FROM public.account
WHERE account_firstname = 'CSE340'
AND account_lastname = 'Motors'
AND account_type = 'Admin'